modLoader="javafml"
loaderVersion="[24,)"
issueTrackerURL="https://github.com/Glitchfiend/BiomesOPlenty/issues"
displayURL="https://minecraft.curseforge.com/projects/biomes-o-plenty"
authors="Adubbz, Forstride"

[[mods]]
    modId="biomesoplenty"
    version="${version}"
    displayName="Biomes O' Plenty"
    description='''
    Adds over 50 new biomes, blocks, and more!
    '''

[[dependencies.biomesoplenty]]
    modId="forge"
    mandatory=true
    versionRange="[24,)"
    ordering="NONE"
    side="BOTH"